export const GETUSERLIST = 'getUserList'
export const USERLOGIN = 'userLogin'
export const GETCURRENTUSER = 'getCurrentUser'
export const GETNICKNAME = 'getNickname'
export const SHOWSLIDE = 'showSlide'
export const CLOSESLIDE = 'closeSlide'
